### ISSUE TITLE
Abitlity to modify BeeInput in overriden _run() method in bee agend

### ISSUE THREAD

**Issue by mhdawson** [i-am-bee/bee-agent-framework#107]
**Is your feature request related to a problem? Please describe.**
In the use case I was working with I needed to modify  the system prompt
in my _run() method for some invocations before calling super.run().

I  ended up having to modify the state of the agent (this.input.templates.system) before
calling super.run() and then restore the state afterwards. This works and seems to be
ok since the agent currently enforces that only one request is running at time, but
its not ideal.

**Describe the solution you'd like**
Adding another parameter 'beeInput: BeeInput = this.input' the value of which would then be used in
this line - https://github.com/i-am-bee/bee-agent-framework/blob/9054deb30c59986186410667bc2852e9595033b4/src/agents/bee/agent.ts#L105C3-L106C1
instead of this.input or something along those lines.

**Describe alternatives you've considered**
Modifying the agent state (this.input.templates.system) before/after calling super._run()

**Additional context**
I'm not sure if my case will be common enough to warrant the change but if you think it would be useful I'm happy to submit a PR.

**Comment by Tomas2D** [comment]
You can modify the template like this without overriding the agent's behavior.

See: https://github.com/i-am-bee/bee-agent-framework/blob/main/examples/agents/bee_advanced.ts#L40-L45

**Comment by Tomas2D** [comment]
You can modify input/output by registering callback for events (think of it as middleware).

See https://i-am-bee.github.io/bee-agent-framework/#/emitter?id=agent-usage

**Comment by mhdawson** [comment]
@Tomas2D I figured out I could modify the default prompt when the agent was created but I want to modify it not for all interactions but just for some specific ones based on analysis of the question itself.

I don't think the ways you mention allow you to do that, but if you think they can I'll take another look.

**Comment by mhdawson** [comment]
To make it a bit more concrete this is what I'm doing:

```JavaScript
async _run(input, options, run) {
    if (CHECK_FUNCIONS_RELEVANCE) {
      const useFunctions = await this.functionsRelevant(input.prompt, this.memory.messages);
      if (!useFunctions) {
        // modifying the state of the agent is not ideal but works
        // because the agent only allows one request to be executing
        // at a time.
        if (!this.input.templates)
          this.input.templates = {};
        this.input.templates.system = this.noToolsPrompt;
      }
    };

    let result;
    try {
      result = await super._run(input, options, run);
    } finally {
      // restore the modified state
      this.input.templates = this.originalTemplates;
    }
    return result;
  }
}
```

**Comment by Tomas2D** [comment]
I see. So, would you like an override parameter for each iteration? This is a very specific usage, and I don't see any way to smoothly integrate it into the framework without overcomplicating it. Hence, your solution is fine.

**Comment by mhdawson** [comment]
Ok so the suggestion is just to keep doing what I'm doing versus adding an another paramter, right? If so I'll close this issue.

**Comment by Tomas2D** [comment]
From v0.0.34, you can override `BeeAgentRunner` with your custom one, which may help. But we will not add new parameters to the `run` / `_run` method right now.
