### ISSUE TITLE
Requirement on nwa

### ISSUE THREAD

**Issue by grahamwhiteuk** [i-am-bee/bee-agent-framework#11]
**Describe the bug**
`scripts/copyright.sh` has a dependency on an nwa command which I'm guessing could be [this project](https://github.com/B1NARY-GR0UP/nwa).  However, this is not a standard command and there's no method of installing it through this project at present.  We should either remove our dependency on this tool or find a way of integrating it with the developer workflow (even if that involves writing some developer instructions that say how it should be installed). 

**To Reproduce**
Perform a git commit that in turn runs the pre-commit checks and thus the script in question is executed.

**Expected behavior**
It should be clear how to install the required tools or the installation of required tools should be automated

**Comment by Tomas2D** [comment]
I agree. As a fallback, I added auto installation via `go` or running a `Docker` container.
