### ISSUE TITLE
Dependencies issue (Couldn't find package X required by Y) on Mac M1

### ISSUE THREAD

**Issue by barvhaim** [i-am-bee/bee-agent-framework#112]
Hi, I've just getting started with running the example locally on my Mac M1, cloned the project and ran `nvm install` & `nvm use` to get the required node, and then `npm install`, the installation failed with the error: 
```
error Couldn't find package "@rollup/rollup-freebsd-arm64@4.24.1" required by "rollup@^4.24.0" on the "npm" registry.
```

**To Reproduce**

1. Clone the project and cd to the project
2. nvm install
3. nvm use
4. npm install

**Expected behavior**
Expected the installation to complete successfully 

**Screenshots / Code snippets**
If applicable, add screenshots or code snippets to help explain your problem.
<img width="1066" alt="image" src="https://github.com/user-attachments/assets/2d80ea78-3f53-4de5-9e6d-849640a696ae">

**Set-up:**

- Bee version:  v0.0.33
- Mac M1

**Comment by barvhaim** [comment]
might be related https://github.com/vitejs/vite/issues/18481

**Comment by barvhaim** [comment]
I've added 
```
"resolutions": {
    "rollup": "4.24.0"
  }
```
to package.json
and it completed the installation successfully 

(https://github.com/vitejs/vite/issues/18481#issuecomment-2439896338)

<img width="538" alt="image" src="https://github.com/user-attachments/assets/283eb9b8-78a2-4164-b40e-f8a66aa5a47e">

**Comment by Tomas2D** [comment]
Hello @barvhaim,

this package should be used with `yarn` and not `npm`. Could you try to install dependencies with `yarn` as stated in README?

**Comment by barvhaim** [comment]
@Tomas2D thanks, sorry, can close
