### ISSUE TITLE
Pull Request template

### ISSUE THREAD

**Issue by grahamwhiteuk** [i-am-bee/bee-agent-framework#12]
**Is your feature request related to a problem? Please describe.**
There is currently no Pull Request template.  This issue is to discuss whether one is needed,

**Describe the solution you'd like**
Potential for adding a PR template, should it be deemed a good idea.  GitHub [seem to](https://github.com/i-am-bee/bee-agent-framework/community) recommend them.

**Describe alternatives you've considered**
The project remains without a PR template.

**Additional context**
I'm happy to PR a template into the repo if it's decided to go ahead.

**Comment by Tomas2D** [comment]
I will be glad for you to do it 🚀
