### ISSUE TITLE
Use SSG for documentation pages

### ISSUE THREAD

**Issue by Tomas2D** [i-am-bee/bee-agent-framework#137]
Right now, all documentation is rendered on the client side via Javascript. 

We want pre-render documentation at the build time (SSG), which should be doable with doscify.

**Comment by adigidh** [comment]
Is it okay to take a first stab at this issue? 

Agreed that doccify is lightweight, but have you had a chance to look at `gatsby-theme-carbon`? Ref: https://www.npmjs.com/package/gatsby-theme-carbon

Well this also depends on the requirement & the use case for the scalability of the doc site, and if you'd like hot reloading, automatic code splitting, faster performance. The gatsby theme with carbon offers for usage of carbon components directly on the site. The combination of React and Gatsby's ecosystem is powerful yet complex.

**Comment by Tomas2D** [comment]
We will soon be working on a custom UI, hence closing this for now.
