### ISSUE TITLE
OOTB Granite Bee Agent

### ISSUE THREAD

**Issue by mmurad2** [i-am-bee/bee-agent-framework#145]
**Is your feature request related to a problem? Please describe.**
I want to be able to easily get started with a Bee agent that uses Granite-3.0-8B-Instruct, and be able to use most of the functionality that Bee provides OOTB.

**Describe the solution you'd like**
OTTB bee agent implementation and ideally a way to easily swap models for a Bee agent
Add docs as well

**Describe alternatives you've considered**
NA

**Additional context**
Related ticket: https://github.com/i-am-bee/bee-agent-framework/issues/70

**Comment by geneknit** [comment]
Documentation update needed, then ready to ship.
