### ISSUE TITLE
Support Milvus (Vector DB) as a tool

### ISSUE THREAD

**Issue by Tomas2D** [i-am-bee/bee-agent-framework#158]
- Create a tool called `Milvus` in `src/tools/database/milvus.ts` (ideally with tests)
- Inspiration could be an `Elasticsearch` tool.

Resources
- Reading: https://i-am-bee.github.io/bee-agent-framework/#/CONTRIBUTING
- Reading: https://i-am-bee.github.io/bee-agent-framework/#/tools?id=writing-a-new-tool

**Comment by adigidh** [comment]
Is it okay to take a first stab at this issue?

Was thinking to do the following:

- Have Milvus  running with Docker 
- Wire up milvus with the JS side of things (setup, connect to an instance, creating & listing basic collection)
- Basic utils for inserting and searching for vectors

any other items to tackle on this issue, @Tomas2D ?

**Comment by Tomas2D** [comment]
Hello @adigidh. 

That would be great. I updated the issue description. Setting up Docker should not be part of the repository; the rest is fine. Feel free to ask or open a draft PR, and we can discuss it.

**Comment by Tomas2D** [comment]
Released in v0.0.44
