### ISSUE TITLE
typeorm legacy Dependency issue

### ISSUE THREAD

**Issue by krishnac7** [i-am-bee/bee-agent-framework#17]
**Describe the bug**
trying to install the bee-agent framework into a react project, but facing the following issue

 ```
Could not resolve dependency:
npm error peerOptional typeorm@"^0.3.20" from @langchain/community@0.2.32```

**Comment by Tomas2D** [comment]
LangChain is a **peer dependency** of `bee-agent-framework` and is unnecessary. Or do you need it for some reason?
If not, you can ignore this error.

**Comment by Tomas2D** [comment]
Resolved @krishnac7?
