### ISSUE TITLE
Append schema to LLM-generated queries using Sequelize schema option (Postgres)

### ISSUE THREAD

**Issue by jose-biescas** [i-am-bee/bee-agent-framework#173]
Hi team!

**Is your feature request related to a problem? Please describe.**
The `SQLTool` gets so close to correctly generating the query, but it fails because it omits the schema. Postgres has a default `search_path` of `public`.

**Describe the solution you'd like**
If a `schema` option is passed to the `SQLTool` class (and in turn to Sequelize), utilize the `schema` when generating the query. Using schemas different than `public` is very common. From my understanding, if it fails the first time, the `SQLTool` calls the `getMetadataQuery` function to pass in the `schema` for the database. But I'm not sure if it does this on the first try, not that it should, but if we can at least pass the `schema` on the first try, I think it would be more likely to nail the queries on the first try.

**Describe alternatives you've considered**
I think this can be solved in two ways at least:
1. Pass the `schema` name to the LLM as context when tasked to generate the query based on the prompt/question sent by the user. This could allow the LLM to always prefix table names with the schema provided.
2. Post-process the query and manually insert the schema.

**Additional context**
![image](https://github.com/user-attachments/assets/f38f30c2-4882-4011-88b4-a53840afc1e6)
In the image above, the query was correct! But unfortunately it failed because the `schema` name was omitted.

![image](https://github.com/user-attachments/assets/777f07a3-f194-410d-8471-1247486a2ddd)
It then actually tried using the default `public` schema.

Given the list of supported databases, I know that not all of them work the same way. I do believe that some like Db2 also work this way, where the schema needs to be prefixing the table name to be able to access it.

That being said, I used Llama3.1:8b as my model, would have to test using different models.

**Comment by Tomas2D** [comment]
Hello. @abughali, as the tool's author, do you have any thoughts on this?

**Comment by abughali** [comment]
Dear @jose-biescas 

Thank you for the detailed explanation of the issue. I see three possible solutions:

1. If you are using EDB, consider creating a public synonym for the table names.
2. Alter the database search path.
3. Advise the agent to add the schema name as a prefix to the table names. This can be done in the prompt by including a guideline like: "Always add the schema name 'your_schema' to fully qualify table names."

Please let us know if none of the above options are viable.

cc: @Tomas2D

**Comment by abughali** [comment]
Dear @jose-biescas,

For your information, I will enhance the SQLTool to minimize roundtrips to the LLM.

**Current behavior:**

1. Question
2. Query (most likely wrong)
3. Get metadata
4. Query (hopefully correct)

**Proposed enhancement:**

1. Question
2. Get metadata
3. Query (hopefully correct) — at this step, we can advise the LLM to append the schema name.

Best regards,
cc: @Tomas2D

**Comment by jose-biescas** [comment]
Hi @abughali 

Thank you for the quick reply and providing the alternatives. I think the 3rd option would be the most viable for my team, but will definitely discuss the other two options.

For the 3rd option, (I can't test it right now, will definitely try on Monday) would it be possible to intercept the thought of the agent? So adding the guidance "Always add the schema name to fully qualify table names" to the prompt once the agent thinks to use the SQLTool?

Either way, I appreciate the proposed enhancement!

Thank you for looking into this.

**Comment by abughali** [comment]
@jose-biescas 

I created a PR for this issue. The schema name is being added now on the second attempt.

![Image 2024-11-17 at 12 28 AM](https://github.com/user-attachments/assets/67a7c190-3c68-4a04-adaf-71b147b7c12c)

**Comment by abughali** [comment]
@jose-biescas the code which resolved this issue has been merged. Can we close it now?

**Comment by jose-biescas** [comment]
@abughali Yes! Just saw the PR, thank you very much!

**Comment by abughali** [comment]
@Tomas2D @mmurad2 I think we good to close this issue.

**Comment by Tomas2D** [comment]
The fix has been released in version 0.0.41. Please verify @jose-biescas and close this issue if it is fixed.
