### ISSUE TITLE
`ibm/granite-instruct` preset for the IBMvLLM adapter is vague and resolves incorrect max_sequence_length

### ISSUE THREAD

**Issue by michael-desmond** [i-am-bee/bee-agent-framework#190]
**Describe the bug**
The `ibm/granite-instruct` preset for the IBMvLLM adapter is not specific to the model being used. I assume its `ibm-granite/granite-3.0-8b-instruct` and should be named as such to avoid confusion. 

Assuming `ibm-granite/granite-3.0-8b-instruct` then the backend returns the incorrect max_sequence_length of `8192`. The correct max_sequence_length is `4096`

**To Reproduce**

1. Create an GraniteBeeAgent with IBMvLLM backend using preset `ibm/granite-instruct`
2. Breakpoint the `meta` method in the corresponding llm.ts
3. Result will indicate a `max_sequence_length` of 8192

**Expected behavior**
`max_sequence_length` of 4096

**Screenshots / Code snippets**
![Screenshot 2024-11-21 at 10 24 22 AM](https://github.com/user-attachments/assets/219f1280-b374-4e0d-953d-ccd0f932d671)

**Set-up:**

- Bee version: 0.0.41
- Model provider: IBMvLLM

**Comment by Tomas2D** [comment]
Our backend returns `4096` for `ibm/granite-instruct`.

Regarding naming cc @jezekra1

**Comment by michael-desmond** [comment]
I had them replace the backend llm with the correct version from huggingface i.e. https://huggingface.co/ibm-granite/granite-3.0-8b-instruct, this fixed the sequence length issue.

**Comment by michael-desmond** [comment]
I think changing the name would require a simultaneous fix in the framework to expose the new name via chat preset.

**Comment by Tomas2D** [comment]
Could you submit a PR, then?

**Comment by michael-desmond** [comment]
Yes, ill sync with backend and get a PR in.

**Comment by Tomas2D** [comment]
Any update? @michael-desmond
