### ISSUE TITLE
Granite runner check not general enough for ollama

### ISSUE THREAD

**Issue by michael-desmond** [i-am-bee/bee-agent-framework#216]
**Describe the bug**
The check that chooses a granite runner for BeeAgent is not general enough to work with ollama which has a model_id `granite3-dense:8b`. 

The check: https://github.com/i-am-bee/bee-agent-framework/blob/834aca99a0192467101ce903448c42f5aa76bc73/src/agents/bee/agent.ts#L68

[granite3-dense](https://ollama.com/library/granite3-dense)

**To Reproduce**

1. Create a BeeAgent with ollama llm configured for `granite3-dense:8b`
2. Breakpoint the agent
3. It uses the DefaultRunner
 
**Expected behavior**
It should use the GraniteRunner.

**Screenshots / Code snippets**
![image](https://github.com/user-attachments/assets/4cdc2553-fd45-41da-91fe-5982ddc14f09)

**Set-up:**

- Bee version: 0.0.43
- Model provider: ollama

**Comment by michael-desmond** [comment]
Ill PR a fix for this today.

**Comment by Tomas2D** [comment]
Great. Then we should make a change to Bee API (https://github.com/i-am-bee/bee-api/blob/6ca4bf436e6b77d44b4d2939ef705aacca82984e/src/runs/execution/factory.ts#L264)

**Comment by michael-desmond** [comment]
I ended up with the same check in the Bee API, so I guess we can just leave that be?
