### ISSUE TITLE
Add agent documentation page

### ISSUE THREAD

**Issue by mmurad2** [i-am-bee/bee-agent-framework#26]
**Is your feature request related to a problem? Please describe.**
It's unclear when to use each of `maxRetriesPerStep`, `totalMaxRetries`, `maxIterations` and how these concepts interact with each other.

**Describe the solution you'd like**
Add documentation on one, and add examples.

**Comment by akihikokuroda** [comment]
@Tomas2D Hi!  I'm looking for something I can start contributing to this project.  This issue is marked as "good first issue".  If you don't mind, I want to try this.  Is it OK?
