### ISSUE TITLE
OpenMeteo tool geocoding fails to produce a result, and provides unhelpful error message

### ISSUE THREAD

**Issue by michael-desmond** [i-am-bee/bee-agent-framework#36]
**Describe the bug**
For certain location names the OpenMeteo tool internal geocoding fails, and the tool throws an unhelpful Tool error message.

**To Reproduce**

1. Call the openMeteo tool using location name as "White Plains NY" or "Windsor CT" or "Las Vegas NV".
2. The tool will return a Tool Error
```
ToolError: Tool "OpenMeteo" has occurred an error!
    TypeError: Cannot read properties of undefined (reading '0')
```
3. Seems like the geocoding api has some internal search logic that produces no results when qualifiers are included in the location name. For example "Limerick, Ireland" works but "Limerick Ireland" does not. 
4. The tool checks for `response.ok` from the geocoding api, but does not check for no results and indexes into an empty array. 

**Expected behavior**
The tool error should check for empty geocoding result and produce a more informative error message, perhaps indicating that the agent recheck the location name, limiting it to the place name only. 

**Set-up:**

- Bee version: v0.0.18
- Model provider: BAM

**Comment by Tomas2D** [comment]
Thanks for the report.

Fix has been released in 0.0.19
