### ISSUE TITLE
Add cache use examples

### ISSUE THREAD

**Issue by mmurad2** [i-am-bee/bee-agent-framework#44]
**Is your feature request related to a problem? Please describe.**
Understand how and when to use the different [cache](https://github.com/i-am-bee/bee-agent-framework/blob/main/docs/overview.md#cache) implementations available in the framework

**Describe the solution you'd like**
Showcase the different memory strategies in action with examples

**Comment by Tomas2D** [comment]
Done: https://github.com/i-am-bee/bee-agent-framework/blob/main/docs/cache.md
