### ISSUE TITLE
Update default examples to llama3.2

### ISSUE THREAD

**Issue by mmurad2** [i-am-bee/bee-agent-framework#47]
**Background**
Our current default examples are implemented with llama3.1 as the LLM used. Now that [llama3.2](https://ai.meta.com/blog/llama-3-2-connect-2024-vision-edge-mobile-devices/) dropped we want to update the core examples in the repo.

**What to update**
- [ ] https://github.com/i-am-bee/bee-agent-framework?tab=readme-ov-file#example
- [ ] https://github.com/i-am-bee/bee-agent-framework/blob/main/examples/llms/providers/ollama.ts
- [ ] https://github.com/i-am-bee/bee-agent-framework/blob/main/examples/agents/bee_advanced.ts
- [ ] https://github.com/i-am-bee/bee-agent-framework/blob/main/examples/agents/bee.ts
- [ ] https://github.com/i-am-bee/bee-agent-framework/blob/main/examples/agents/sql.ts
- [ ] https://github.com/i-am-bee/bee-agent-framework/blob/main/examples/llms/providers/watsonx.ts
- [ ] https://github.com/i-am-bee/bee-agent-framework/blob/main/examples/llms/providers/watsonx_verbose.ts

**Acceptance criteria**
- [ ] Validate that the model swap doesn't impact the performance of the example. Compare example performance before and after switch.

**Comment by Abiji-2020** [comment]
@mmurad2  Interested in working on this issue could you assign this to me so that i can work on it ?

**Comment by Tomas2D** [comment]
Great @Abiji-2020!

Firstly you need to define the model template in `src/adapters/shared/llmChatTemplates.ts`. then you have to updates presets for BAM and WatsonX, finally update the examples.

**Comment by Abiji-2020** [comment]
@Tomas2D I have updated the templates and then updated the presets for the both. The PR #51 was updated on that
