### ISSUE TITLE
Podman containers are not started

### ISSUE THREAD

**Issue by nheidloff** [i-am-bee/bee-agent-framework#8]
When running ...

```
corepack yarn run infra:start-code-interpreter
```

... the Podman containers are not launched.

It works when I run this command directly:

```
podman compose up bee-code-interpreter
```

$docker_cmd is set correctly to "podman". The .env file exists.

I use zsh on MacOS.

**Comment by Tomas2D** [comment]
Can you verify with the latest commit? There was a [little bug](https://github.com/i-am-bee/bee-agent-framework/commit/51961afb8a610c224d023bf2e0dd5bec2e02c1a4) preventing the script from executing if there was an existing `.env` file.
