### ISSUE TITLE
"yarn format:fix" makes "yarn lint" an error 

### ISSUE THREAD

**Issue by akihikokuroda** [i-am-bee/bee-agent-framework#87]
**Describe the bug**

Code before the `yarn format:fix` that passes the `yarn lint`
```
      console.log({ // eslint-disable-line no-console
        path: example,
        stdout,
      });
```
`yarn format` issues warnings for this
```
yarn format
Checking formatting...
[warn] tests/examples/examples.test.ts
[warn] Code style issues found in the above file. Run Prettier with --write to fix.
```
Then `yarn format:fix` change this code to
```
      console.log({
        // eslint-disable-line no-console
        path: example,
        stdout,
      });
```
`yarn lint` issues an error and a warning for this code
```
/Users/akihikokuroda/development/repositories/agenticflow/bee-agent-framework/tests/examples/examples.test.ts
  40:7  error    Unexpected console statement                                                   no-console
  41:9  warning  Unused eslint-disable directive (no problems were reported from 'no-console')

✖ 2 problems (1 error, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.
```

**To Reproduce**

Refer to Describe the bug

**Expected behavior**
`yarn lint` and `yarn format` should not conflict each other.

**Screenshots / Code snippets**

**Set-up:**
Code level: commit b86629803bc1e3f65aaf1aefad2382053e3f27cd (origin/main, origin/HEAD, main)

**Additional context**

**Comment by Tomas2D** [comment]
This issue relates to `eslint-config-prettier.`

However, the solution is easy. Use `// eslint-disable-next-line no-console` instead.

```typescript
// eslint-disable-next-line no-console
console.log();
```

**Comment by akihikokuroda** [comment]
Works great!  Thanks!
