### ISSUE TITLE
Wrong warning in example for code interpreter

### ISSUE THREAD

**Issue by nheidloff** [i-am-bee/bee-agent-framework#9]
Just a detail. This error comes up in bee.ts even if the env variable is defined.

```
System Please ensure that the code interpreter is running.
```

The check needs to be inverse: https://github.com/i-am-bee/bee-agent-framework/blob/7ebad1fbcd5514fed3610da3025bfb2e5ea7d9e3/examples/agents/bee.ts#L51

**Comment by Tomas2D** [comment]
This is intended. 

You can have ENV set (so PythonTool becomes activated), but the container may not be running.
If the ENV is not set, then the code interpreter is not used, and thus, you can't get any error from the `PythonTool` (because it is not used).

**Comment by nheidloff** [comment]
Oh, that's a little confusing. How about changing the message to something more descriptive?

"The code interpreter is enabled. Please ensure that it is running on http://localhost:50051."

**Comment by Tomas2D** [comment]
Agree, updated.

Ref: https://github.com/i-am-bee/bee-agent-framework/commit/ea28b43b8a1aad3f51d191b4f7179a3672888c4f
