### ISSUE TITLE
the final answer in agents.md is strange

### ISSUE THREAD

**Issue by akihikokuroda** [i-am-bee/bee-agent-framework#99]
**Describe the bug**
In the agents.md file, it explains ReAct approach.  The example output of "Second iteration" that generates the final answer is putting a wrong answer.

```
thought: "I have the current weather in Las Vegas. I can now provide the user with the current temperature and other weather information."
final_answer: "The first commercial typewriter was invented in 1874.";
```
**To Reproduce**

Look at https://github.com/i-am-bee/bee-agent-framework/blob/main/docs/agents.md#bee-agent
or 
https://i-am-bee.github.io/bee-agent-framework/#/agents

**Expected behavior**
I believe that the final_answer should be the weather in Las Vegas

**Screenshots / Code snippets**

**Set-up:**

Look at [github repo](https://i-am-bee.github.io/bee-agent-framework/#/agents) or [the doc site](https://i-am-bee.github.io/bee-agent-framework/#/agents)

Latest commit is: 8a128a186fd5dd32e52c4396ba5603ff85ab674a

**Comment by akihikokuroda** [comment]
Is this intentional?

**Comment by Tomas2D** [comment]
No, it is not. Thank you for the report. Fixed.
